# Generated by Django 5.1.5 on 2025-04-12 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_sendimg_imgpath'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sendimg',
        ),
        migrations.DeleteModel(
            name='verfiedusers',
        ),
    ]
