# Generated by Django 3.1 on 2025-04-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_delete_sendimg_delete_verfiedusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_table',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
