# Generated by Django 5.1.5 on 2025-04-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20250414_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_table',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
